### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joshspicer**
fun fact, github pages regenerates the `_site` folder on each deploy, so that's actually the only folder that doesn't matter :)

https://stackoverflow.com/a/33176486/10846506

### CODE REVIEW

**Comment by DTxCode** [comment]
Neat.

Could we also then delete the _site folder and add it to .gitignore?

**Comment by joshspicer** [comment]
yeeep. I suggest adding this gitignore

https://github.com/github/gitignore/blob/master/Jekyll.gitignore

**Comment by DTxCode** [comment]
Removed _site and updated gitignore. @joshspicer looks good?

**Comment by joshspicer** [comment]
looks good to me!

**Pull request merged**
